disabled_rules:
  - trailing_comma
  - vertical_whitespace
  - trailing_whitespace
  - unused_closure_parameter
  - closure_parameter_position
  - missing_docs
  - force_try

leading_whitespace:
  severity: error

opt_in_rules:
  - empty_count
  - missing_docs

included:
  - Projects/${TARGET_NAME}

excluded:
  - Pods
  - Projects/${TARGET_NAME}/Resources/R.generated.swift

analyzer_rules:
  - unused_import
  - unused_private_declaration

force_cast: error
force_try:
  severity: error

cyclomatic_complexity:
  - 15

line_length:
  - 120

function_body_length:
  - 100
  - 200

function_parameter_count:
  - 10
  - 15

large_tuple:
  - 6
  - 12

type_body_length:
  - 300
  - 400

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    error: 2
    warning: 3
  excluded:
    - id
    - x
    - y
    - f
    - xs
    - s
    - m
    - l
    - xl
  allowed_symbols:
    - _
  validates_start_with_lowercase: false

reporter: "xcode" # 보고 유형 (xcode, json, csv, checkstyle, junit, html, emoji, markdown)
